WisdomMarketResearch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
# from report.sitemaps import ReportSitemap
from report.views import (indexView,categoryPage,publisherPage,aboutus,contactus,
                          latestReports,thankyouPage,search_report_list,servicesPage,subscribeForm,
                          privacyPolicy,termsandconditions,index_header,become_publisher,publisher_list,success,research_methodology,refund_policy)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView, name='index'),
    path('index/', index_header, name='indexheader'),
    path('latest-reports', latestReports, name='latestreports'),
    path('about-us', aboutus, name='aboutus'),
    path('research-methodology', research_methodology, name='research_methodology'),
    path('refund-policy', refund_policy, name='refund_policy'),
    path('contact-us', contactus, name='contactus'),
    path('thank-you', thankyouPage, name='thankyou'),
    path('search-reports', search_report_list, name='search_report_list'),
    path('services', servicesPage, name='services'),
    path('privacy-policy', privacyPolicy, name='privacypolicy'),
    path('terms-and-conditions', termsandconditions, name='termsandconditions'),
    path('category/<slug:slug>', categoryPage, name='category'),
    path('publisher/<slug:slug>', publisherPage, name='publisher'),
    path('publisher', publisher_list, name='publisher_list'),
    path('become-publisher', become_publisher, name='becomepublisher'),
    path('subscribe', subscribeForm, name='subscribe'),
    path('success', success, name='success'),
    path('', include('report.urls', namespace='reports')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type="text/plain"),),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path,include
from report.views import (reportPage,requestSample,checkout,requestInquiry,
                          requestDiscount,paymentComplete,covid_request,indexcheckout,thanks,thanksDiscount,thanksInquiry)
app_name = 'reports'

urlpatterns = [

    path('<slug:slug>', reportPage, name='reportpage'),
    path('request-sample/<str:id>', requestSample, name='samplerequest'),
    path('thanks/request-sample/<str:id>', thanks, name='thanks'),
    path('request-discount/<str:id>', requestDiscount, name='discountrequest'),
    path('thanks/request-discount/<str:id>', thanksDiscount, name='thanksDiscount'),
    path('request-inquiry/<str:id>', requestInquiry, name='inquiryrequest'),
    path('thanks/request-discount/<str:id>', thanksInquiry, name='thanksInquiry'),
    path('covid19-request/<str:id>', covid_request, name='covidrequest'),
    path('checkout/<int:id>', checkout, name='checkout'),
    path('checkout/<int:id>/<int:price>', indexcheckout, name='indexcheckout'),
    path('payment/complete', paymentComplete, name='complete'),



]

report/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string

from .forms import LeadForm, CheckoutForm, ContactForm, BecomePublisherFrom
from .models import Category, Report, Publisher, SliderImage, OurClients, Billing_Details
from django.db.models import Q
from django_countries import countries
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
import json
import requests


def indexView(request):
    reports = Report.objects.all().order_by('-published_date')[:3]
    cat_count = Category.objects.all().count()
    cat_count1 = int(cat_count // 4)
    categories1 = Category.objects.all().order_by("name")[0:8]
    categories2 = Category.objects.all().order_by("name")[8:]

    publishers = Publisher.objects.all().order_by("name")
    query = request.GET.get('searchReport')
    slider = SliderImage.objects.all()
    clients = OurClients.objects.all()

    return render(request, 'base/index.html',
                  {'reports': reports, 'categories1': categories1,'categories2': categories2, 'slider': slider,
                   'publishers': publishers, 'clients': clients})


def aboutus(request):
    return render(request, 'base/about-us.html')


def servicesPage(request):
    return render(request, 'base/services.html')


def research_methodology(request):
    return render(request, 'base/research_methodology.html')


def refund_policy(request):
    return render(request, 'base/refund-policy.html')


def thanks(request,id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            lead_form = form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Sample'
            if request.POST['comment'] == "":
                lead_form.comment = ""
            lead_form.save()
            message = 'Report Code:' + report.publisher.publisher_code + '-' + str(
                report.id) + '\n\n' + 'Report Name:' + report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email: ' + lead_form.corporate_email + '\n\n' + 'Phone:' + str(
                lead_form.phone) + '\n\n' + 'Country:' + str(
                lead_form.country) + '\n\n' + 'Category:' + report.category.name + '\n\n' + 'Publisher :' + report.publisher.name + '\n\n' + 'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title + '\n\n' + 'Price:' + str(
                report.single_user_price) + '\n\n' + 'Comments:' + lead_form.comment
            subject = 'Lead - Sample Request'
            send_email(sender_email, sender_password, recipient_email, subject, message)
    return render(request,'report/thanks.html')

def thanksDiscount(request,id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            lead_form = form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Discount'
            if request.POST['comment'] == "":
                lead_form.comment = ""
            lead_form.save()
            message = 'Report Code:' + report.publisher.publisher_code + '-' + str(
                report.id) + '\n\n' + 'Report Name:' + report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email: ' + lead_form.corporate_email + '\n\n' + 'Phone:' + str(
                lead_form.phone) + '\n\n' + 'Country:' + str(
                lead_form.country) + '\n\n' + 'Category:' + report.category.name + '\n\n' + 'Publisher :' + report.publisher.name + '\n\n' + 'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title + '\n\n' + 'Price:' + str(
                report.single_user_price) + '\n\n' + 'Comments:' + lead_form.comment
            subject = 'Lead - Sample Request'
            send_email(sender_email, sender_password, recipient_email, subject, message)
    return render(request, 'report/thanks.html')


def thanksInquiry(request,id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            lead_form = form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Inquiry'
            if request.POST['comment'] == "":
                lead_form.comment = ""
            lead_form.save()
            message = 'Report Code:' + report.publisher.publisher_code + '-' + str(
                report.id) + '\n\n' + 'Report Name:' + report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email: ' + lead_form.corporate_email + '\n\n' + 'Phone:' + str(
                lead_form.phone) + '\n\n' + 'Country:' + str(
                lead_form.country) + '\n\n' + 'Category:' + report.category.name + '\n\n' + 'Publisher :' + report.publisher.name + '\n\n' + 'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title + '\n\n' + 'Price:' + str(
                report.single_user_price) + '\n\n' + 'Comments:' + lead_form.comment
            subject = 'Lead - Sample Request'
            send_email(sender_email, sender_password, recipient_email, subject, message)
    return render(request, 'report/thanks.html')

def contactus(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            emailBody = 'Full Name:' + request.POST['full_name'] + '\n\n' + 'Corporate Email:' + request.POST[
                'corporate_email'] + '\n\n' + 'Phone:' + request.POST['phone'] \
                        + '\n\n' + 'Subject: ' + request.POST['subject'] + '\n\n' + 'Message:' + request.POST['message']
            send_mail(
                'Contact Us Request',
                emailBody,
                'sales@wisdommarketresearch.com',
                ['leads@affluencemarketreports.com'],
                fail_silently=False,
            )

            return redirect('thankyou')
    return render(request, 'base/contact-us.html', {'form': form})


def reportPage(request, slug):
    report = get_object_or_404(Report, slug=slug)
    category = report.category
    cat_report = Report.objects.filter(category=category)[:5]
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            lead_form = form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Sample'
            if request.POST['comment'] == "":
                lead_form.comment = ""
            lead_form.save()
            message = 'Report Code:' + report.publisher.publisher_code + '-' + str(
                report.id) + '\n\n' + 'Report Name:' + report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email: ' + lead_form.corporate_email + '\n\n' + 'Phone:' + str(
                lead_form.phone) + '\n\n' + 'Country:' + str(
                lead_form.country) + '\n\n' + 'Category:' + report.category.name + '\n\n' + 'Publisher :' + report.publisher.name + '\n\n' + 'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title + '\n\n' + 'Price:' + str(
                report.single_user_price) + '\n\n' + 'Comments:' + lead_form.comment
            subject = 'Lead - Sample Request'
            # send_mail(
            #     'Lead - Sample Request',
            #     emailBody,
            #     'sales@wisdommarketresearch.com',
            #     ['leads@affluencemarketreports.com'],
            #     fail_silently=False,
            # )
            # send_simple_message(lead_form.full_name, report.title, lead_form.corporate_email)
            send_email(sender_email, sender_password, recipient_email, subject, message)

            return render(request,'report/thanks.html',{'report': report})
        else:
            print('Form invalid')
    else:
        form = LeadForm()

    return render(request, 'report/reportpage.html',
                  {'report': report, 'category': category, 'cat_report': cat_report, 'form': form})


def thankyouPage(request):
    return render(request, 'base/thank-you.html')


def publisher_list(request):
    publishers = Publisher.objects.all().order_by("name")
    return render(request, 'report/publisher_list.html', {'publishers': publishers})


def requestSample(request, id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)

        if form.is_valid():
            lead_form = form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Sample'
            if request.POST['comment'] == "":
                lead_form.comment = ""

            lead_form.save()

            message = 'Report Code:' + report.publisher.publisher_code + '-' + str(
                report.id) + '\n\n' + 'Report Name:' + report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email: ' + lead_form.corporate_email + '\n\n' + 'Phone:' + str(
                lead_form.phone) + '\n\n' + 'Country:' + str(
                lead_form.country) + '\n\n' + 'Category:' + report.category.name + '\n\n' + 'Publisher :' + report.publisher.name + '\n\n' + 'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title + '\n\n' + 'Price:' + str(
                report.single_user_price) + '\n\n' + 'Comments:' + lead_form.comment
            subject = 'Lead - Sample Request'
            # send_mail(
            #     'Lead - Sample Request',
            #      emailBody,
            #     'sales@wisdommarketresearch.com',
            #     ['leads@affluencemarketreports.com'],
            #     fail_silently=False,
            # )

templates/report/category.html
{% extends 'base.html' %}


{% block title %} {{category.name | title}} Reports {% endblock %}

{% block body %}

		<div class="container">
			<div class="text-center">
				<h1 class="head-after h1fs">{{category.name | title}} Reports</h1>
			</div>
			<div class="row">
				<div class="col-lg-3 mb-3">
					<div class="card-d">
						<h4 class="head-after">Reports By Industries</h4>
						<div class="mt-2">
							<ul class="side-nav-bar">
                                {% for allcategory in all_categories %}
								{% if allcategory.name == category.name %}

									<li class="active">
										<a href="{% url 'category' allcategory.slug %}" title="{{allcategory.name}}">
											<strong>{{ allcategory.name }}</strong>
										</a>
									</li>
								{% else %}
								<li>
										<a href="{% url 'category' allcategory.slug %}" title="{{allcategory.name}}">
											<strong>{{ allcategory.name}}</strong>
										</a>
								</li>
								{% endif %}

                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>							
				<div class="col-lg-9">
					<div id="category-card">
                                          {% for report in reports %}
											<div class="card" >
													  <div class="card-body">
														  <a href="{% url 'reports:reportpage' report.slug %}" class="a_underline"><h5 class="card-title" style="color:#10073f"><strong>{{report.title}}</strong></h5></a>
														  <p class="card-text">{{report.summary | truncatechars:250 | safe}}<a class="blc" href="{% url 'reports:reportpage' report.slug %}" ><strong>Read More>></strong></a></p>
														  <p>
												<h5><span class="text-left">Date: {{report.published_date | date:"M Y"}}</span>&nbsp;&nbsp;|
                                                 <span class="text-left">Price: ${{report.single_user_price}}</span>
													  <div class="float-right">
<!--														<form class = "form-inline" method="post" action="{% url 'reports:indexcheckout' report.id report.single_user_price%}">-->
<!--															{% csrf_token %}-->

														<a class="btn btn-success" href="{% url 'reports:samplerequest' report.id%}"><span><i class="fas fa-download"></i> &nbsp; <strong>Request Sample </strong></span></a>
<!--														&nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-primary"><i class="fas fa-shopping-cart"></i>&nbsp;<strong>Buy Now</strong></button>-->
<!--                                                            </form>-->
													</div>
													  </h5>
												</p>

													  </div>
													</div>
					                      {% endfor %}
					</div>
				</div>

			</div>




			  <div class="pagination-btn text-center mt-12">
					     <nav aria-label="Page navigation">
							 <ul class="pagination">
										{% if reports.has_previous %}
										<li class="page-item">
										  <a class="page-link" href="?page=1" aria-label="Previous">
											<span aria-hidden="true">&laquo;</span>
											<span class="sr-only">begin</span>
										  </a>
										</li>   {% endif %}

										{% for n in reports.paginator.page_range %}
										  {% if reports.number == n %}
											<li class="page-item active">
											  <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
											</li>
										  {% elif n > reports.number|add:'-3' and n < reports.number|add:'3' %}
											<li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
										  {% endif %}
										{% endfor %}

										{% if reports.has_next %}
										  <li class="page-item">
											<a class="page-link" href="?page={{ reports.paginator.num_pages }}" aria-label="Next">
											  <span aria-hidden="true">&raquo;</span>
											  <span class="sr-only">end</span>
											</a>
										  </li>
										  {% endif %}   </ul> </nav>
                  </div>

			</div>

		</div>
	</div>
</div>

{% endblock %}

templates/report/covid19-request.html
{% extends 'base.html'%}

{% block title %} COVID 19 Impact Analysis | Wisdom Market Research {% endblock %}

{% block body %}
<body>

<div class="container">
<div class="breadcum_list1">
<nav aria-label="breadcrumb">
<ol class="breadcrumb" style="background-color:white;">
	<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
	<li class="breadcrumb-item"><a href="{% url 'reports:reportpage' report.slug %}">{{report.title}}</a></li>
	<li class="breadcrumb-item active" aria-current="page">COVID 19 Impact</li>
</ol>
</nav>
</div>
<div class="container">
    <div class="row mt-4">
        <div class="col-lg-8 col-md-8 col-sm-12">
			<div class="card">
					  <div class="card-header" style="background-color:#0b9ad7;">
						 <h5 style="color:white;">{{report.title | title}}</h5>
					  </div>
					  <div class="card-body">
						<form method="post">

                            <h4>{{form.errors}}</h4>
						{% csrf_token %}
						{{form.full_name}}
						{{form.corporate_email}}
						{{ form.country }}
						{{ form.phone }}
						{{ form.job_title }}
						{{ form.company }}
						{{ form.comment }}
						<button type='submit' class='btn btn-primary'><strong>Submit</strong></button>
<!--							<button type="submit" class="btn btn-primary">Go somewhere</button>-->

					 </form>

					  </div>
					</div>
        </div>
        <div class="col-lg-4 col-md-8 col-sm-12">
          <div class="card">
                  <div class="card-header" style="background-color:#0b9ad7;color:white">
                      <strong>Why Choose Us ?</strong>
                  </div>
                  <div class="card-body" >

                      <p class="card-text">24/7 Research support</p>
                      <p class="card-text">Quality assurance</p>
                      <p class="card-text">Information security</p>



                  </div>
          </div>
              <div class="card">
                  <div class="card-header" style="background-color:#0b9ad7;color:white">
                      <strong>Support</strong>
                  </div>
                  <div class="card-body" >
 <p><i class="icon-phone"></i>&nbsp; U.S <a href="tel:+1-424-256-1722">&nbsp; +1-(424) 256-1722</a></p>
						  <p><i class="icon-phone"></i>&nbsp; IND<a href="tel:+91-8075755284">&nbsp; +91-8075755284</a></h5></p>

						  <p><i class="icon-envelope"></i><a href='mailto:sales@wisdommarketresearch.com'> &nbsp;<span class="__cf_email__" >sales@wisdommarketresearch.com</span></a></p>




                  </div>
          </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/report/latest-report.html
{% extends 'base.html' %}



{% block title %} Latest Industry Reports {% endblock %}
{% block body %}

		<div class="container">
			<div class="text-center">
				<h1 class="head-after h1fs">Latest Industry Reports</h1>
			</div>
			<div class="row">
				<div class="col-lg-3 mb-3">
					<div class="card-d">
						<h4 class="head-after">Reports By Industries</h4>
						<div class="mt-2">
							<ul class="side-nav-bar">
                                {% for allcategory in all_categories %}
								{% if allcategory.name == category.name %}

									<li class="active">
										<a href="{% url 'category' allcategory.slug %}" title="{{allcategory.name}}">
											<strong>{{ allcategory.name}}</strong>
										</a>
									</li>
								{% else %}
								<li>
										<a href="{% url 'category' allcategory.slug %}" title="{{allcategory.name}}">
											<strong>{{ allcategory.name }}</strong>
										</a>
								</li>
								{% endif %}

                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-9">
    <div id="latest-report-card" class="row">
        {% for report in reports %}
        <div class="card col-lg-12 col-md-6 col-sm-12 mb-4">
            <div class="card-body">
                <a href="{% url 'reports:reportpage' report.slug %}">
                    <h5 class="card-title" style="color:#10073f"><strong>{{report.title}}</strong></h5>
                </a>
                <p class="card-text">{{report.summary | truncatechars:250 | safe }}<a href="{% url 'reports:reportpage' report.slug %}" class="blc"><strong>Read More>></strong></a></p>
                <div class="d-flex justify-content-between mb-3">
                    <span>Date: {{report.published_date | date:"M Y"}}</span>
                    <span>Price: ${{report.single_user_price}}</span>
                </div>
                <div class="text-center text-lg-right">
                    <form method="post" action="{% url 'reports:indexcheckout' report.id report.single_user_price%}">
                        {% csrf_token %}
                        <a class="btn btn-success mb-2 mr-sm-2" href="{% url 'reports:samplerequest' report.id%}"><i class="fas fa-download"></i>&nbsp;<strong>Request Sample</strong></a>
                        <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-shopping-cart"></i>&nbsp;<strong>Buy Now</strong></button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


			</div>





			      <div class="pagination-btn text-center mt-12">
					     <nav aria-label="Page navigation">
							 <ul class="pagination">
										{% if reports.has_previous %}
										<li class="page-item">
										  <a class="page-link" href="?page=1" aria-label="Previous">
											<span aria-hidden="true">&laquo;</span>
											<span class="sr-only">begin</span>
										  </a>
										</li>   {% endif %}

										{% for n in reports.paginator.page_range %}
										  {% if reports.number == n %}
											<li class="page-item active">
											  <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
											</li>
										  {% elif n > reports.number|add:'-3' and n < reports.number|add:'3' %}
											<li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
										  {% endif %}
										{% endfor %}

										{% if reports.has_next %}
										  <li class="page-item">
											<a class="page-link" href="?page={{ reports.paginator.num_pages }}" aria-label="Next">
											  <span aria-hidden="true">&raquo;</span>
											  <span class="sr-only">end</span>
											</a>
										  </li>
										  {% endif %}   </ul> </nav>
                  </div>


			</div>

		</div>
	</div>
</div>

{% endblock %}

templates/report/publisher.html
{% extends 'base.html' %}



{% block title %} {{publisher.name | title}}'s Reports {% endblock %}
{% block body %}

		<div class="container">
			<div class="text-center">
				<h1 class="head-after h1fs">{{publisher.name}}'s Reports</h1>
			</div>
			<div class="row">
				<div class="col-lg-3 mb-3">
					<div class="card-d">
						<h4 class="head-after">Reports By Publishers</h4>
						<div class="mt-2">
							<ul class="side-nav-bar">
                                {% for allpublisher in all_publishers %}
								{% if allpublisher.name == publisher.name %}

									<li class="active">
										<a href="{% url 'publisher' allpublisher.slug %}" title="{{allpublisher.name}}">
											<strong>{{ allpublisher.name }}</strong>
										</a>
									</li>
								{% else %}
								<li>
										<a href="{% url 'publisher' allpublisher.slug %}" title="{{allpublisher.name}}">
											<strong>{{ allpublisher.name }}</strong>
										</a>
								</li>
								{% endif %}

                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>							
				<div class="col-lg-9">
					<div id="publisher-card">
                                          {% for report in reports %}
											<div class="card" >
													  <div class="card-body">
														  <a href="{% url 'reports:reportpage' report.slug %}"> <h5 class="card-title" style="color:#0b9ad7"><strong>{{report.title}}</strong></h5></a>
														  <p class="card-text">{{report.summary | truncatechars:250 | safe | linebreaks }}<a href="{% url 'reports:reportpage' report.slug %}" class="blc"><strong>Read More>></strong></a></p>
														 <p>
												<h5><span class="text-left">Date: {{report.published_date | date:"M Y"}}</span>&nbsp;&nbsp;|
                                                 <span class="text-left">Price: ${{report.single_user_price}}</span>
													  <div class="float-right">
														<form class = "form-inline" method="post" action="{% url 'reports:indexcheckout' report.id report.single_user_price%}">
															{% csrf_token %}

														<a class="btn btn-success" href="{% url 'reports:samplerequest' report.id%}"><span><i class="fas fa-download"></i> &nbsp; <strong>Request Sample </strong></span></a>
														&nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-primary"><i class="fas fa-shopping-cart"></i>&nbsp;<strong>Buy Now</strong></button>
                                                            </form>
													</div>

													  </h5>
												</p>

													  </div>
													</div>
					                      {% endfor %}
					</div>
				</div>

			</div>




			  <div class="pagination-btn text-center mt-12">
					     <nav aria-label="Page navigation">
							 <ul class="pagination">
										{% if reports.has_previous %}
										<li class="page-item">
										  <a class="page-link" href="?page=1" aria-label="Previous">
											<span aria-hidden="true">&laquo;</span>
											<span class="sr-only">begin</span>
										  </a>
										</li>   {% endif %}

										{% for n in reports.paginator.page_range %}
										  {% if reports.number == n %}
											<li class="page-item active">
											  <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
											</li>
										  {% elif n > reports.number|add:'-3' and n < reports.number|add:'3' %}
											<li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
										  {% endif %}
										{% endfor %}

										{% if reports.has_next %}
										  <li class="page-item">
											<a class="page-link" href="?page={{ reports.paginator.num_pages }}" aria-label="Next">
											  <span aria-hidden="true">&raquo;</span>
											  <span class="sr-only">end</span>
											</a>
										  </li>
										  {% endif %}   </ul> </nav>
                  </div>

			</div>

		</div>
	</div>
</div>

{% endblock %}

templates/report/publisher_list.html
{% extends 'base.html' %}



{% block title %} Publisher Listing Page {% endblock %}
{% block body %}

<div class="text-center">
	<h1 class="head-after h1fs">Publishers</h1>
</div>
<div class="container mt-4">
   <div class="row">
       {% for publisher in publishers %}
       <div class="col-lg-3 col-6">
            <div class="mb-3 text-center">
										<a href="{% url 'publisher' publisher.slug %}">
											<div class="card-img-top img-hover-zoom">
											<img alt="{{publisher.name | title }}" title=" {{publisher.name | title }}" src="{{publisher.image.url}}" height="75px" width="150px">
										     </div>
										</a>
									</div>
									<h3 class="text-center" ><a href="{% url 'publisher' publisher.slug %}" style="color:#0b9ad7;">
										<span><strong>{{publisher.name}}</strong></span>
									</a></h3>
       </div>
       {% endfor %}



  </div>

</div>



{% endblock %}

templates/report/thanks.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Thank You | Wisdom Market Research {% endblock %}
{% block body %}
    <div class="container">
    	<div class="jumbotron text-center">
              <h1 class="display-3">Thank You!!</h1>
              <p class="lead"><strong>Our Sales Representative will soon get Back to you.</strong> </p>
              <hr>
              <p>
                Having trouble? <a href="{% url 'contactus' %}" style="color:blue">Contact us</a>
              </p>
              <p class="lead">
                <a class="btn btn-primary " href="{% url 'index' %}" role="button">Continue to homepage</a>
              </p>
            </div>
    </div>
{% endblock %}